import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Dancing_Script } from "next/font/google";
import Navbar from "@/components/ui/shared/Navbar";
import SmoothScrollProvider from "@/components/shared/SmoothScrollProvider";
import GsapProvider from "@/components/shared/GsapProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const dancingScript = Dancing_Script({
  variable: "--font-dancing-script",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title:  "Novara | Premium Accessories",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${dancingScript.variable} h-full antialiased`}
    >
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Tuesday+Night&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="min-h-full flex flex-col">
        <SmoothScrollProvider>
          <GsapProvider>
            <Navbar />
            {children}
          </GsapProvider>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
