import ProductDetail, { type Product } from "@/components/ProductDetail";

const products: Record<string, Product> = {
  "midnight-onyx-chrono": {
    name: "Midnight Onyx Chrono",
    category: "Watches",
    price: "$450.00",
    originalPrice: "$520.00",
    rating: 4.8,
    reviews: 124,
    sold: "442 sold in last 32 hours",
    viewing: 19,
    description: "A masterpiece of precision engineering, this chronograph features a deep onyx dial paired with rose gold accents. Water-resistant up to 100m with sapphire crystal glass.",
    colors: ["#2C2C2C", "#D4B89C", "#8B6B5B"],
    sizes: ["S", "M", "L"],
    sku: "N/A",
    vendor: "Louis Vuitton",
    available: "In stock",
    categories: "Watches",
    images: ["/images/a1.jpg", "/images/a2.avif", "/images/a3avif.avif", "/images/a4.avif"],
  },
  "sienna-tuscan-tote": {
    name: "Sienna Tuscan Tote",
    category: "Bags",
    price: "$520.00",
    originalPrice: "$590.00",
    rating: 4.9,
    reviews: 89,
    sold: "328 sold in last 48 hours",
    viewing: 12,
    description: "Handcrafted from premium Italian leather, this tote embodies timeless elegance. Spacious interior with multiple compartments for everyday luxury.",
    colors: ["#C4A882", "#8B6B5B", "#2C2C2C"],
    sizes: ["One Size"],
    sku: "N/A",
    vendor: "Gucci",
    available: "In stock",
    categories: "Bags",
    images: ["/images/a4.avif", "/images/a1.jpg", "/images/a3avif.avif", "/images/a5.avif"],
  },
  "imperial-gold-bangle": {
    name: "Imperial Gold Bangle",
    category: "Jewelry",
    price: "$310.00",
    originalPrice: "$370.00",
    rating: 4.7,
    reviews: 203,
    sold: "215 sold in last 24 hours",
    viewing: 28,
    description: "18K gold-plated bangle with intricate detailing. A statement piece that complements both casual and formal attire effortlessly.",
    colors: ["#D4B89C", "#2C2C2C", "#8B6B5B"],
    sizes: ["S", "M", "L"],
    sku: "N/A",
    vendor: "Cartier",
    available: "In stock",
    categories: "Jewelry",
    images: ["/images/a3avif.avif", "/images/a1.jpg", "/images/a4.avif", "/images/a6.avif"],
  },
  "obsidian-aviator-shades": {
    name: "Obsidian Aviator Shades",
    category: "Sunglasses",
    price: "$280.00",
    originalPrice: "$340.00",
    rating: 4.6,
    reviews: 156,
    sold: "189 sold in last 36 hours",
    viewing: 9,
    description: "Polarized lenses housed in a lightweight titanium frame. UV400 protection meets contemporary design for the modern gentleman.",
    colors: ["#2C2C2C", "#D4B89C"],
    sizes: ["One Size"],
    sku: "N/A",
    vendor: "Ray-Ban",
    available: "In stock",
    categories: "Sunglasses",
    images: ["/images/a5.avif", "/images/a1.jpg", "/images/a3avif.avif", "/images/a4.avif"],
  },
  "heritage-canvas-weekender": {
    name: "Heritage Canvas Weekender",
    category: "Bags",
    price: "$395.00",
    originalPrice: "$450.00",
    rating: 4.9,
    reviews: 312,
    sold: "412 sold in last 48 hours",
    viewing: 35,
    description: "Waxed canvas meets full-grain leather trim in this rugged yet refined weekender bag. Built to last a lifetime of adventures.",
    colors: ["#8B6B5B", "#C4A882", "#2C2C2C"],
    sizes: ["One Size"],
    sku: "N/A",
    vendor: "Tumi",
    available: "In stock",
    categories: "Bags",
    images: ["/images/a6.avif", "/images/a1.jpg", "/images/a4.avif", "/images/a3avif.avif"],
  },
  "aura-noir-perfume": {
    name: "Aura Noir Perfume",
    category: "Perfumes",
    price: "$185.00",
    originalPrice: "$220.00",
    rating: 4.8,
    reviews: 97,
    sold: "267 sold in last 24 hours",
    viewing: 22,
    description: "Notes of black oud, amber, and smoky vetiver create an intoxicating signature scent. Long-lasting 12-hour fragrance profile.",
    colors: ["#2C2C2C"],
    sizes: ["One Size"],
    sku: "N/A",
    vendor: "Tom Ford",
    available: "In stock",
    categories: "Perfumes",
    images: ["/images/a2.avif", "/images/a1.jpg", "/images/a4.avif", "/images/a6.avif"],
  },
};

export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const product = products[slug] || products["midnight-onyx-chrono"];

  return <ProductDetail product={product} allProducts={Object.values(products)} />;
}
